version: '3'
services:
    db_pg:
        build: 
            context: ./db/
            dockerfile: DockerfileDB_PG
        ports:
            - "5432:5432"
            #  api:
            #build:
            #context: ./api
            #dockerfile: DockerfileServer
